[package]
name = "quantum_safe_multisig"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-sign = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
rust-pkcs11 = "0.4.1"

